# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish

on:
  # Manually publish release
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to bump `package.json` to
      tag:
        required: false
        description: Tag of publish package
        default: "latest"
      publish:
        required: false
        description: Whether to publish to register
        default: "true"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Install rollup.js
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build --if-present

      - name: Publish to npm
        if: github.event.inputs.publish == 'true'
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: ${{ github.event.inputs.tag }}

      - name: Create Release
        if: success() && steps.publish.outputs.type != 'none' && github.event.inputs.publish == 'true'
        id: create_release
        uses: ncipollo/release-action@v1.8.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.publish.outputs.version }}
          name: Release v${{ steps.publish.outputs.version }}
          body: ${{ steps.publish.outputs.version }}
          draft: false
          prerelease: false
