# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rollup.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Install rollup.js
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build --if-present
      - name: Publish beta to npm
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "beta-v%s"
          tag_message: "beta-v%s"
          create_tag: "true"
          commit_pattern: "^build(version): beta (\\S+)"
          workspace: "."
          publish_command: "pnpm"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
